/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nokdoo' at '2/6/17 11:22 PM' with Gradle 3.0
 *
 * @author nokdoo, @date 2/6/17 11:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
